Repository payw-org/eodiro, pull requests merged in 2019-09, with the labels that each got.

#123 Endgame/meal
  .eslintrc.js
  package.json
  src/assets/styles/scss/global/globalstyle.scss
  src/assets/styles/scss/utilities/_mixins.scss
  src/assets/styles/scss/utilities/_variables.scss
  src/components/global/Banner.vue
  src/components/ui/blocks/Accordion.vue
  src/lang/meals/ko-KR.js
  src/pages/index.vue
  src/pages/meals/index.vue
  src/pages/preferences.vue
  src/plugins/init.ts
  src/plugins/topbar.js
  src/store/index.js
  yarn.lock
Labels: enhancement, feature, fix

#125 Reconstruct pages with components
  src/components/meals/MealTimeGroup.vue
  src/pages/meals/index.vue
Labels: enhancement

#127 Test the hall of fame
  src/assets/styles/scss/utilities/_functions.scss
  src/lang/donation/en-US.js
  src/lang/donation/ko-KR.js
  src/pages/donation.vue
Labels: feature

#131 Yarn to npm
  .gitignore
  src/lang/community/en-US.js
  src/lang/community/ko-KR.js
  src/pages/community/new.vue
  yarn.lock
Labels: refactor

#135 Refactor banner
  package-lock.json
  package.json
  src/assets/styles/stylus/spring.styl
  src/components/global/Banner.vue
  src/mixins/page-base.js
  src/pages/vacant/_buildingId/_floorId/index.vue
  src/plugins/custom-event-manager.ts
Labels: refactor

#137 Refactor/banner
  src/assets/styles/scss/global/transition.scss
  src/components/global/Banner.vue
  src/mixins/page-base.js
Labels: enhancement, fix, refactor

#138 fix: flickering banner when go to page depth > 1
  src/components/global/Banner.vue
  src/mixins/page-base.js
  src/pages/search-class.vue
Labels: fix

#145 Use meals API
  src/components/meals/MealTimeGroup.vue
  src/modules/extend-route.js
  src/pages/index.vue
  src/pages/inquiry.vue
  src/pages/meals.vue
  src/pages/meals/_date.vue
Labels: feature

#148 Hotfix for beta 1 release
  package-lock.json
  package.json
  src/components/global/Banner.vue
  src/components/meals/MealTimeGroup.vue
  src/lang/inquiry/en-US.js
  src/lang/inquiry/ko-KR.js
  src/pages/index.vue
  src/pages/inquiry.vue
  src/pages/meals/_date.vue
  src/pages/vacant/_buildingId/_floorId/index.vue
  src/pages/vacant/_buildingId/index.vue
  src/pages/vacant/index.vue
  src/plugins/eodiro-dialog/index.ts
Labels: fix

#151 feat: dist script
  package.json
Labels: feature

#153 Fix "dist" script and disable restaurant menu
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  package.json
  src/pages/index.vue
Labels: fix

#154 Update icons
  src/static/apple-touch-icon.png
  src/static/icon.png
Labels: fix

#155 Bump up font version and disable lighter weights
  src/assets/styles/css/fonts.css
Labels: fix

#157 Ignore yarn-error.log
  .gitignore
  yarn-error.log
Labels: fix

#159 Fix distribution script
  package.json
Labels: fix

#160 fix: enable meals
  src/pages/index.vue
Labels: fix

#162 fix: meals -> meals-date
  src/pages/index.vue
Labels: fix

#163 Dev
  src/pages/index.vue
Labels: fix

#164 fix: fix dist script
  package.json
Labels: fix

#165 Fix favicon
  nuxt.config.js
  src/static/android-chrome-192x192.png
  src/static/android-chrome-512x512.png
  src/static/apple-touch-icon.png
  src/static/browserconfig.xml
  src/static/favicon-16x16.png
  src/static/favicon-32x32.png
  src/static/favicon.ico
  src/static/icon-192.png
  src/static/icon-512.png
  src/static/mstile-150x150.png
  src/static/safari-pinned-tab.svg
Labels: fix

#166 Update meals UI
  src/components/global/Banner.vue
  src/components/meals/MealTimeGroup.vue
  src/components/ui/blocks/Accordion.vue
  src/static/fonts/Inter/Inter-ExtraBold.woff
  src/static/fonts/Inter/Inter-ExtraBold.woff2
Labels: fix

#168 Fix some minor issues
  src/components/global/Banner.vue
  src/components/meals/MealTimeGroup.vue
  src/components/ui/blocks/Accordion.vue
Labels: fix

#169 Update meals
  src/components/global/Banner.vue
  src/components/meals/MealTimeGroup.vue
Labels: enhancement

#171 Update banner
  src/components/global/Banner.vue
Labels: enhancement

#172 Fix and update miscellaneous
  nuxt.config.js
  package.json
  src/components/global/Banner.vue
  src/components/meals/MealTimeGroup.vue
  src/components/ui/blocks/Accordion.vue
  src/static/android-chrome-192x192.png
  src/static/android-chrome-512x512.png
  src/static/apple-touch-icon.png
  src/static/browserconfig.xml
  src/static/favicon-16x16.png
  src/static/favicon-32x32.png
  src/static/favicon.ico
  src/static/fonts/Inter/Inter-ExtraBold.woff
  src/static/fonts/Inter/Inter-ExtraBold.woff2
  src/static/icon-192.png
  src/static/icon-512.png
  src/static/mstile-150x150.png
  src/static/safari-pinned-tab.svg
Labels: enhancement, fix

#173 Improve stability
  nuxt.config.js
  src/components/global/Banner.vue
  src/components/home/HomeBgTile.vue
Labels: enhancement

#174 Improve stability of the banner
  nuxt.config.js
  src/components/global/Banner.vue
  src/components/home/HomeBgTile.vue
Labels: enhancement

#178 Add opensource page information
  src/assets/images/github/logo-inverted.svg
  src/assets/images/github/logo-original.svg
  src/lang/opensource/en-US.js
  src/lang/opensource/ko-KR.js
  src/lang/utils/getLang.js
  src/pages/opensource.vue
Labels: feature

#180 fix: add dark mode github icon
  src/pages/opensource.vue
Labels: fix

#182 Try to resolve safari favorite icon
  nuxt.config.js
  src/static/apple-touch-icon-120.png
  src/static/apple-touch-icon-152.png
  src/static/apple-touch-icon-512.png
  src/static/apple-touch-icon-76.png
  src/static/icon-120.png
  src/static/icon-144.png
  src/static/icon-152.png
  src/static/icon-192.png
  src/static/icon-384.png
  src/static/icon-512.png
  src/static/icon-64.png
  src/static/site.webmanifest
Labels: fix
